import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'

import { Video } from '../types'
import VideoCard from '../components/VideoCard'
import NoResults from '../components/NoResults'

interface IProps {
  videos: Video[];
}

const Home = ({ videos }: IProps) => {
  // console.log(videos)
  return (
    <div>
      <Head>
        <title>Dolmo Shorts - India&apos;s Favourite Short Video Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dolmo-icon.png" />
      </Head>

      <div className='flex flex-col gap-10 videos h-full'>
        {videos.length ? (
          videos.map((video: Video) => (
            <VideoCard post={video} isShowingOnHome key={video._id} />
          ))
        ) : (
          <NoResults text={'No Videos'} />
        )}
      </div>

    </div>
  )
}

export const getServerSideProps = async () => {

  const { data } = await axios.get(`${process.env.NEXT_PUBLIC_HOST}/api/post`);

  return {
    props: {
      videos: data
    }, // will be passed to the page component as props
  }
}

export default Home
